pipeline {
  agent any

  environment {
    PROJECT_DIR = "${WORKSPACE}"
  }

  stages {
    stage('Run ETL Step by Step') {
      steps {
        bat 'jenkins\\run_job.bat'
      }
    }
  }

  post {
    always {
      bat """
        echo Cleaning up workspace contents...

        REM Hapus semua file di root
        del /f /q "${WORKSPACE}\\*"

        REM Hapus semua subfolder
        for /d %%x in ("${WORKSPACE}\\*") do rd /s /q "%%x"

        echo Cleanup complete.
      """
    }
  }
}
